server:
  port: 12000

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/data_collection_annotation_app
      username: root
      password: wang1207 #注意格式
      # url: jdbc:mysql://206.189.35.98:3306/data_collection_annotation_app
      # username: weiju
      # password: 123456 #注意格式

    resources:
        chain:
          enabled: true
          cache: true