server:
  port: 12000

spring:
    datasource:
      url: jdbc:mysql://206.189.35.98:3306/data_collection_annotation_app
      username: weiju
      password: 123456

    resources:
        chain:
          strategy:
            content:
              enabled: true

          enabled: true
          cache: true
jwt:
  header: "Authorization"
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: /auth
      refresh: /refersh


myip: 206.189.35.98